replicaCount: 1

image:
  repository: karlz007/auth-service-go
  tag: latest

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

env:
  DATABASE_HOST: auth-service-postgresql.default.svc.cluster.local
  DATABASE_PORT: 5432
  DATABASE_URL: "postgres://authuser:authpass@auth-service-postgresql.default.svc.cluster.local:5432/authdb?sslmode=disable"
  JWT_SECRET: "whyisitsohard"

postgresql:
  auth:
    username: authuser
    password: authpass
    database: authdb
  primary:
    persistence:
      enabled: false
